# Токен телеграмм бота
telegramToken: ''

# Подключение к базе данных
database:
    host: 'localhost:3306'
    username: 'root'
    password: 'qwerty123'
    database: 'knasu'

# Переопределение кодов учебных групп.
# В ходе разработки было замечено, что в приказе "об утверждении КУГ"
# иногда может не быть кодов для некоторых групп, поэтому их можно добавить отдельно здесь.
# Формат: "название_группы": "код_группы"
# "название группы" - чувствителен к регистру
# Если такого случая не существует, то оставить "{}"
groupCodes: {}
